function registerHelp(bot) {
  bot.command('help', async (ctx) => {
    const minConf    = process.env.MIN_CONFIDENCE || '65';
    const interval   = Math.round(parseInt(process.env.SCAN_INTERVAL || '60000') / 1000);

    const msg = [
      `❓ <b>AZZAVISION AI v5.0 — PANDUAN LENGKAP</b>`,
      ``,
      `━━━━━━━━━━━━━━━━━━`,
      `🤖 <b>DUAL AI ENGINE</b>`,
      ``,
      `<b>1️⃣ Signal Engine</b>`,
      `• Mencari trigger realtime XAUUSD`,
      `• Monitoring TP, SL, Breakeven, Trailing`,
      `• Trade Journal + Performance Report`,
      `• H4 + H1 searah, Entry rejection candle M5`,
      `• Self-learning dari dataset trade selesai`,
      ``,
      `<b>2️⃣ Trade Scanner AI (BARU v5.0)</b>`,
      `• Memberikan SETUP MARKET (bukan entry realtime)`,
      `• SHORT (1-8 jam) | MEDIUM (1-3 hari) | LONG (1-2 minggu)`,
      `• Signal Lifecycle: WAITING → ACTIVE → TP/SL/EXPIRED`,
      `• Signal Lock: 1 sinyal aktif per tipe`,
      `• Risk Management: LOW/MEDIUM/HIGH + RR + Lot`,
      `• AI Strategy Description + High Confluence Alert`,
      ``,
      `━━━━━━━━━━━━━━━━━━`,
      `⚙️ <b>RISK MANAGEMENT</b>`,
      ``,
      `🛑 SL     : 40 points (Signal Engine)`,
      `💰 TP1    : 60 points`,
      `💰 TP2    : 125 points`,
      `🔒 Breakeven: saat profit ≥ 28 points`,
      `ℹ️ BE = BUKAN LOSS — dihitung terpisah`,
      ``,
      `━━━━━━━━━━━━━━━━━━`,
      `📋 <b>PERINTAH UMUM</b>`,
      ``,
      `/market      — Kondisi market semua timeframe`,
      `/stats       — Statistik performa (WIN/LOSS/BE)`,
      `/daily       — Laporan hari ini`,
      `/daily7      — Ringkasan 7 hari`,
      `/journal     — Riwayat sinyal`,
      `/backtest 7  — Backtest 7 hari`,
      `/status      — Status bot`,
      `/help        — Panduan ini`,
      ``,
      `━━━━━━━━━━━━━━━━━━`,
      `🔭 <b>TRADE SCANNER AI (v5.0)</b>`,
      ``,
      `/scan         — Menu utama scanner`,
      `/scan short   — Setup SHORT (1-8 jam)`,
      `/scan medium  — Setup MEDIUM (1-3 hari)`,
      `/scan long    — Setup LONG (1-2 minggu)`,
      `/scan status  — Signal scanner aktif`,
      `/scan history — Histori scanner`,
      ``,
      `━━━━━━━━━━━━━━━━━━`,
      `📚 <b>E-BOOK ENGINE</b>`,
      ``,
      `/ebookstrats — Lihat semua strategi e-book aktif`,
      `/ebook       — Download koleksi e-book Forex`,
      ``,
      `━━━━━━━━━━━━━━━━━━`,
      `🧠 <b>LEARNING COMMANDS</b>`,
      ``,
      `/learnstats  — Status learning dataset`,
      `/similarity  — Similarity setup saat ini`,
      ``,
      `━━━━━━━━━━━━━━━━━━`,
      `🔑 <b>API KEY ROTATION</b>`,
      ``,
      `/apikeys     — Status semua API key (✅⏳❌)`,
      `/aitest      — Health check semua AI provider`,
      ``,
      `━━━━━━━━━━━━━━━━━━`,
      `🔐 <b>OWNER ONLY</b>`,
      ``,
      `/forcebuy    — Force sinyal BUY`,
      `/forcesell   — Force sinyal SELL`,
      `/retrain     — Sinkronisasi dataset`,
      `/scan        — Trade Scanner + Signal Engine scan`,
      `/signaltest  — Tes kirim sinyal ke channel`,
      `/reload      — Reload & cek konfigurasi`,
      `/backup      — Backup manual`,
      `/selftest    — Self-test semua modul`,
      ``,
      `━━━━━━━━━━━━━━━━━━`,
      `🤖 <b>AI ROUTER v5.0</b>`,
      ``,
      `News          → Gemini`,
      `Reasoning     → OpenRouter`,
      `Fast Chat     → Groq`,
      `Emergency     → Offline AI`,
      `Auto-fallback : Gemini → OpenRouter → Groq → Offline`,
      ``,
      `━━━━━━━━━━━━━━━━━━`,
      `⚠️ <i>Confidence minimum: ${minConf}%</i>`,
      `<i>Scan interval: ${interval}s</i>`,
      `<i>Learning aktif setelah 30 trades selesai</i>`,
      `<i>API Key rotation: round-robin otomatis</i>`,
      `<i>E-Book Engine: aktif secara otomatis (hybrid)</i>`,
      ``,
      `⚡ <i>AZZAVISION AI v5.0 — AI Trading Assistant</i>`,
      `<i>Dual Engine: Signal Engine + Trade Scanner AI</i>`,
    ].join('\n');

    await ctx.replyWithHTML(msg);
  });
}

module.exports = { registerHelp };
